### ISSUE TITLE
JWT Decoding: expirationDate

### ISSUE THREAD

**Issue by vpapanchev** [w3c/vc-jwt#7] opened 2022-04-28 13:12 UTC
Hi,

I believe there is a small mistake in the [JWT Decoding section](https://www.w3.org/TR/vc-data-model/#jwt-decoding).

It says that the **exp** property of a JWT Credential must be used to set the value of the **expirationDate** of **credentialSubject** of the new JSON object.
If I am not mistaken, it should be used to set the value of the **expirationDate** of the new credential JSON object.

**Comment by selfissued** [comment] 2022-10-13 20:17
I believe that @vpapanchev 's observation is correct.

**Comment by Sakurann** [comment] 2023-01-16 07:07
can this be closed as a duplicate of issue #39?

**Comment by OR13** [comment] 2023-06-30 22:22
closing as dupe

**Closed by OR13** 2023-06-30 22:22 UTC
